### PR TITLE
Refactor to use export groups

### PR DESCRIPTION
**Pull request by Kubulambula**
This PR refactors the `monitor_overlay` to use export annotations instead of the property list hack.

### CODE REVIEW

**Comment by HungryProton** [comment]
Thanks for the PR
The only thing that bothers me with it is you removed all the setters that forced the UI to regenerate when a variable changes.

**Comment by Kubulambula** [comment]
> Thanks for the PR The only thing that bothers me with it is you removed all the setters that forced the UI to regenerate when a variable changes.

Ah, sorry. I messed up the branch creation. I'm going to fix it right away

**Comment by Kubulambula** [comment]
Should be good now

**Comment by HungryProton** [comment]
Thank you!

**Pull request merged**
